### ISSUE TITLE
horizon allows choosing floating ip network for VM

### ISSUE THREAD

**Issue by AbelNavarro** [midokura/midonet-openstack#20]
Floating IP networks are required by quantum in order to offer floating IPs. That network should be hidden though to en users when launching VMs. It should only be available when assigning floating IPs.

Steps to reproduce:
1. Create tenant network
2. Create floating IP network
3. Launch instance -> network tab

Here you can see how two networks are offered: dev-network and public. Public should be hidden.

![Screen Shot 2013-02-26 at 3 47 56 PM](https://f.cloud.github.com/assets/1333236/196653/a01cc6d6-8023-11e2-9923-e395b5e151a9.png)

**Comment by adjohn** [comment]
Floating IPs is not supported in Horizon in Folsom, see the doc here under "Known Issues":
http://docs.openstack.org/developer/horizon/releases/2012_2.html

You will need to use the quantum CLI in order to associate floating IPs.   Also please do not kill a VM without disassociating the floating IP via quantum first, or you will run into troubles. :)

**Comment by AbelNavarro** [comment]
I think you are referring to issue #21. This one is a bit different, we don't want to associate floating IPs here, but prevent to show the external network.

**Comment by adjohn** [comment]
Ah yes, sorry my mistake.  The external network (created via quantum) never
showed up for me in the past, that is weird.  Can you post the specific commands you used for each step?

**Comment by AbelNavarro** [comment]
I was following Captain's doc on how to create the floating IP network. This is the section from that document I used (changing tokens, IDs and IPs):

```
# Create Tenant Network
quantum --os_token 7928e48770484483827df9fdb73afaca --os_url http://localhost:9696/ net-create net1
quantum --os_token 7928e48770484483827df9fdb73afaca --os_url http://localhost:9696/ subnet-create subnet1 10.0.0.0/24
# Create Floating IP Network 
quantum --os_token 7928e48770484483827df9fdb73afaca --os_url http://localhost:9696/ net-create public --router:external=True
quantum --os_token 7928e48770484483827df9fdb73afaca --os_url http://localhost:9696/ subnet-create public 14.128.23.0/27
# Create Tenant Router
quantum --os_token 7928e48770484483827df9fdb73afaca --os_url http://localhost:9696/ router-create router1
# Connect Tenant bridge to Tenant Router
quantum --os_token 7928e48770484483827df9fdb73afaca --os_url http://localhost:9696/ router-interface-add router1 <subnet1-uuid>
# Connect Tenant Router to Provider Router
quantum --os_token 7928e48770484483827df9fdb73afaca --os_url http://localhost:9696/ router-gateway-set router1 <ext-net-id>
```

**Comment by adjohn** [comment]
I followed these directions and things worked fine:
http://docs.openstack.org/trunk/openstack-network/admin/content/demo_logical_network_config.html
